---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(tidyverse)
library(plotly)
library("p8105.datasets")
library(flexdashboard)

knitr::opts_chunk$set(
	fig.width = 6, 
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

Column {data-width=650}
-----------------------------------------------------------------------

```{r data}
rest_inspec =
  rest_inspec %>% 
   filter(grade %in%  c("A", "B", "C"), boro != "Missing") %>%
   sample_n(5000)


```


### Distribution of Restaurant Grades by Borough

```{r grades}

rest_inspec %>%
  select(boro, grade)  %>%
  plot_ly(x = ~boro, color = ~grade, type = "histogram", colors = "Set3" ) %>%
  layout(
    title = "Distribution of Restaurant Grades (A, B, C) by Borough",
    xaxis = list(title = "Borough"),
    yaxis = list(title = "Restaurant Grade")
  )
```

Column {data-width=350}
-----------------------------------------------------------------------

### Distribution of Restaurant Inspection Scores by Borough

```{r scores}
rest_inspec %>%
  plot_ly(
    y = ~score, color = ~boro, type = "box", colors = "Set2") %>%
  layout(
    title = "Distribution of Restaurant Insepction Scores by Borough",
    xaxis = list(title = "Borough"),
    yaxis = list(title = "Restaurant Inspection Score")
  )
  
```

### Chart C

```{r}

```

