---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---
```{r setup, include=FALSE}
library(tidyverse)
library(plotly)
library("p8105.datasets")
library(flexdashboard)


```

```{r data}
rest_inspec =
  rest_inspec %>% 
   filter(grade %in%  c("A", "B", "C"), boro != "Missing") %>%
   sample_n(5000)
```

Column {data-width=550}
-----------------------------------------------------------------------
### Restaurant Grades in Total Dataset (Bar Graph)

```{r grades, warning = FALSE}

rest_inspec %>%
  count(grade) %>%
  plot_ly(x = ~grade, y = ~n, color = ~grade, type = "bar", colors = "Set3" ) %>%
  layout(
    title = "Total Distribution of Restaurant Grades (A, B, C)",
    xaxis = list(title = "Restaurant Grade"),
    yaxis = list(title = "Number of Grades Awarded")
  )


```

Column {data-width=650}
-----------------------------------------------------------------------

### Restaurant Inspection Scores by Borough (Boxplot)

```{r scores}
rest_inspec %>%
  plot_ly(
    y = ~score, color = ~boro, type = "box", colors = "Set2") %>%
  layout(
    title = "Distribution of Restaurant Inspection Scores by Borough",
    xaxis = list(title = "Borough"),
    yaxis = list(title = "Restaurant Inspection Score")
  )
  
```

### Restaurant Inspection Scores and Grades by Borough (Scatterplot)

```{r scatter, message = FALSE}


rest_inspec %>%
  plot_ly(
    x = ~score, y = ~boro, type = "scatter", color = ~grade, colors = "Set1") %>%
   layout(
    title = "Distribution of Restaurant Inspection Scores and Grades by Borough",
    xaxis = list(title = "Restaurant Inspection Score"),
    yaxis = list(title = "Borough")
  )

```

